# Generated by Django 4.2.1 on 2023-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.IntegerField(),
        ),
    ]
